services:
    dh_artis_package_manager_bundle.command.add_trait:
        class: DH\ArtisPackageManagerBundle\Console\Command\AddTraitCommand
        arguments:
            - "@parameter_bag"
        tags:
            - { name: console.command, command: artis:add-traits }

    dh_artis_package_manager_bundle.command.remove_trait:
        class: DH\ArtisPackageManagerBundle\Console\Command\RemoveTraitCommand
        arguments:
            - "@parameter_bag"
        tags:
            - { name: console.command, command: artis:remove-traits }

    dh_artis_package_manager_bundle.command.install_package:
        class: DH\ArtisPackageManagerBundle\Console\Command\InstallPackageCommand
        arguments:
            - "@parameter_bag"
        tags:
            - { name: console.command, command: artis:package:install }

    dh_artis_package_manager_bundle.command.remove_package:
        class: DH\ArtisPackageManagerBundle\Console\Command\RemovePackageCommand
        arguments:
            - "@parameter_bag"
        tags:
            - { name: console.command, command: artis:package:remove }

    dh_artis_package_manager_bundle.command.add_package_config:
        class: DH\ArtisPackageManagerBundle\Console\Command\AddPackageConfigCommand
        arguments:
            - "@parameter_bag"
        tags:
            - { name: console.command, command: artis:add-package-config }

    dh_artis_package_manager_bundle.command.remove_package_config:
        class: DH\ArtisPackageManagerBundle\Console\Command\RemovePackageConfigCommand
        arguments:
            - "@parameter_bag"
        tags:
            - { name: console.command, command: artis:remove-package-config }
